-- Create table to log reaction game sessions (start/end events)
create table if not exists public.reaction_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text,
  client_id text,
  event text check (event in ('start','end')) not null,
  difficulty text check (difficulty in ('easy','medium','hard')),
  rounds int,
  avg_ms int,
  hits int,
  times_ms jsonb,
  time_limit_sec int,
  initial_grid int,
  started_at_ms bigint,
  ended_at_ms bigint,
  user_agent text,
  path text
);

-- Performance indexes for analytics
create index if not exists idx_reaction_sessions_created_at on public.reaction_sessions (created_at desc);
create index if not exists idx_reaction_sessions_event on public.reaction_sessions (event);
create index if not exists idx_reaction_sessions_difficulty on public.reaction_sessions (difficulty);
create index if not exists idx_reaction_sessions_sid on public.reaction_sessions (session_id);

-- Enable RLS and allow anonymous inserts (adjust as needed)
alter table public.reaction_sessions enable row level security;

do $$ begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'reaction_sessions' and policyname = 'allow_anon_insert_reaction_sessions'
  ) then
    create policy allow_anon_insert_reaction_sessions on public.reaction_sessions
      for insert to anon with check (true);
  end if;
end $$;

-- Optional: read-only dev policy (remove in prod if undesired)
-- create policy allow_read_all_reaction_sessions on public.reaction_sessions for select using (true);

-- 게임 총 횟수 테이블 (난이도 무관)
create table if not exists public.game_total_count (
  id bigint generated by default as identity primary key,
  total_games bigint not null default 0,
  last_updated timestamptz not null default now()
);

-- 초기값 설정 (테이블이 비어있을 때만)
insert into public.game_total_count (total_games) 
select 0 where not exists (select 1 from public.game_total_count);

-- 게임 시작할 때마다 총 횟수 증가하는 함수
create or replace function public.increment_total_game_count()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare new_total bigint;
begin
  -- 테이블이 비어있으면 초기값 삽입
  if not exists (select 1 from public.game_total_count) then
    insert into public.game_total_count (total_games) values (1);
    return 1;
  end if;
  
  -- 기존 레코드 업데이트
  update public.game_total_count 
  set total_games = total_games + 1, last_updated = now()
  returning total_games into new_total;
  
  return new_total;
end;
$$;

-- 권한 설정
revoke all on function public.increment_total_game_count() from public;
grant execute on function public.increment_total_game_count() to anon, authenticated;

-- RLS 활성화 및 정책 설정
alter table public.game_total_count enable row level security;

-- 읽기 전용 정책 (총 게임 횟수 조회용)
create policy "allow_read_game_total_count" on public.game_total_count
  for select to anon, authenticated
  using (true);

-- 업데이트는 함수를 통해서만 가능 (increment_total_game_count 함수가 security definer로 실행)

-- Example aggregations you can run in SQL editor:
-- 1) 총 플레이 수
--   select count(*) from public.reaction_sessions where event = 'start';
-- 2) 난이도별 종료 세션 통계
--   select difficulty,
--          count(*) as sessions,
--          avg(rounds) as avg_rounds,
--          percentile_disc(0.5) within group (order by avg_ms) as p50_avg_ms
--     from public.reaction_sessions
--    where event = 'end'
-- group by difficulty
-- order by difficulty;
-- 3) 총 게임 횟수 확인
--   select total_games, last_updated from public.game_total_count;

